### PR TITLE
Made possible to add text even with maxSize

### PR DESCRIPTION
**Pull request by msender**

### CODE REVIEW

**Comment by vadimsva** [comment]
I don't do this for some reason. Text doesn't fit to container. See example with "Horizontal text position", they use maxSize and textPos = 'horizontal'

**Comment by msender** [comment]
Hi,

Is it possible you should add it?
also the maxSize option dosen't work good in internet explorer, it gets
shifted to the left, maby tou shoud use the trasform style instead of the
zoom style.
also if you can please add a fontSize option for the text.

Thanks a lot, It's an amazing utility.

**Comment by vadimsva** [comment]
Hi, use new version

**Comment by msender** [comment]
Thanks

**Pull request closed without merging**
